apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.name" . }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
  selector:
    app: {{ .Release.Name }}
    tier: frontend