apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis_master.name }}
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: {{ .Values.redis_master.service.port }}
    targetPort: {{ .Values.redis_master.service.targetPort }}
  selector:
    app: redis
    role: master
    tier: backend