apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis_slave.name }}
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: {{ .Values.redis_slave.service.port }}
    targetPort: {{ .Values.redis_slave.service.targetPort }}
  selector:
    app: redis
    role: slave
    tier: backend